spring.application.name=UberBackendChief
server.port=8080

#mysql
spring.datasource.url=jdbc:mysql://localhost:3306/uberdatabase
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORDuber}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#json web tokens
jwt.secret=${JWT_SECRETuber}
jwt.expiration=86400

#swagger config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs